### PR TITLE
Add method to disable AMFI with root patches and add information about using AMD GPUs on Ivy Bridge

### PR DESCRIPTION
**Pull request by xCuri0**
Using this method on my system, electron apps and everything works

image

### CODE REVIEW

**Comment by 5T33Z0** [comment]
Awesome. Thanks.

**Comment by 5T33Z0** [comment]
I think I need to add a boot-arg for NVIDIA Kepler GPUss as well so they run in VESA mode until the driver is installed. I had NVIDIA GPUs in the past and if I recall correctly they just turned off after upgrading macOS since webdrivers weren't installed.

**Comment by xCuri0** [comment]
I didn't test without `_apfs_filevault_allowed` and `_authenticate_root_hash` patches also. It could be that those are also required for booting with AMFI enabled

**Comment by 5T33Z0** [comment]
I've added the NVDIA stuff to the guide

On my laptop, I've added and enabled the Kernel Patches for Disabling Library Ealidation Enforcement and the "Disable _csr_check() in _vnode_check_signature", but Ventura won't boot with AMFI enabled. I guess it's because of the requirement for the iGPU. Will have to run some more tests.

**Comment by 5T33Z0** [comment]
Okay: on my Laptop I need `ipc_control_port_options=0` so Firefox and electron-based Apps work with the Intel HD 4000. 

And I need `amfi_get_out_of_my_way=0x1` so the system boots. Maybe the Kernel Patch to disable Library Validation Enforcement no longer works with the latest beta?

**Comment by xCuri0** [comment]
@5T33Z0 
These are the patches I'm using
image

with boot-args `alcid=1 -cryptbeta -wegnoigpu revpatch=memtab,pci,sbvmm`

Electron and everything works. You only need `ipc_control_port_options=0` if AMFI is disabled, it's not related to any patches

**Comment by 5T33Z0** [comment]
I tried those. The patch in Line 11 is only required when using FileVault, which I dont. Like I said: I tested the other kernel patches. When using an iGPU, disabling these boot-args, the system won't boot!

`-crypbeta` is for unsupported versions of macOS (macOS14 basically). macOS 13 is covered in Cryptexfixup
`-wegnoigpu` deactivatsd the iGPU – it's for Desktops with a GPU. But this guide covers Laptops as well. If you would add this to a Laptop config, the screen would turns off…

**Comment by xCuri0** [comment]
@5T33Z0 I tested without the Filevault patch and yeah I'm still able to boot so it doesn't matter.

I guess AMFI can only be enabled for non-AVX2 patch because the others add missing drivers. Thanks for telling about `-cryptbeta`, I didn't know it wasn't needed.

**Comment by 5T33Z0** [comment]
All the boot-args of kexts containing "beta" are for skipping macOS version checks so they will be loaded regardless. That's usually the case when a new macOS is released and the devs haven't had the time yet to update them.

**Comment by xCuri0** [comment]
Even the "Disable Root Hash validation", is not required for me. So might want to change it to AMFI can be disabled if ONLY using non-AVX2 patches for supported AMD GPUs (anything that adds files seems to cause issues so pre-Polaris won't work too)

Screenshot 2023-05-12 at 1 54 55 PM

**Comment by 5T33Z0** [comment]
Some of OCLP's Kernel Patches are only a necessity for real Macs. I guess these:

- Patch IOHIDFamily
- Patch AppleSMC
- Disable Root Hash validation. Seems to be related to apfs security and only required on [real Macs]( https://forums.macrumors.com/threads/macos-13-ventura-on-unsupported-macs-thread.2346881/page-14?post=31200984#post-31200984)

Can you boot with the Patches in Line 13 and 14 disabled?

**Comment by xCuri0** [comment]
@5T33Z0 the only patches I'm using are the 2 in the screenshot. Disabling any of them results in boot failure

**Comment by 5T33Z0** [comment]
Which CPU and SMBIOS are you using?

**Comment by xCuri0** [comment]
@5T33Z0 MacPro7,1 i5 3470

**Comment by 5T33Z0** [comment]
`iMac13,2` would be suited much better in terms of CPU Power Management.

**Comment by xCuri0** [comment]
iMac SMBIOS breaks DRM for me, but I will try Mac Pro (2013) SMBIOS

**Comment by 5T33Z0** [comment]
iMac support iGPUs as well. In this case remove the `-wegnoigpu` as well, so QuickSync video works. Your CPU model was actually used by appel in the iMac13,2: https://everymac.com/systems/apple/imac/specs/imac-core-i5-3.2-27-inch-aluminum-late-2012-specs.html

**Pull request merged**
