### PR TITLE
[PTSWAKTTS Renames] Added missing BaseSkip

### PR DESCRIPTION
**Pull request by dreamwhite**
Fixed formatting and added missing BaseSkip entry

### CODE REVIEW

**Comment by 5T33Z0** [comment]
Thanks.

**Comment by dreamwhite** [comment]
Going to draft another PR for other .plist that are unmaintained. Stay tuned

**Comment by 5T33Z0** [comment]
The formatting inconsistancies are usually introduced by Plist Edit Pro. They don't do harm.

**Comment by dreamwhite** [comment]
> The formatting inconsistancies are usually introduced by Plist Edit Pro. They don't do harm.

alright, but ocvalidate fails on most of the configs

**Comment by 5T33Z0** [comment]
Users can just let OCAT handle to config migration by clicking the save button. But Nobody uses them anyway. People are more focussed about talking shit on reddit about using OCAT than actually appreciating the resources and tools for what they can do. They don't really deserve all these goodies at this stage…

**Pull request merged**
