### PR TITLE
add samples

### PR DESCRIPTION
**Pull request by iamyounix**
just add one sample as learning curve

### CODE REVIEW

**Comment by 5T33Z0** [comment]
Thanks for your contribution. But can you rename them to "SSDT-ALL_example" please? I don't want user to get the impression that they can use these files for their systems.

**Comment by iamyounix** [comment]
noted

**Review by iamyounix — COMMENTED** [review]
done rename

**Comment by 5T33Z0** [comment]
Thanks. Merged.

**Pull request merged**
