### PR TITLE
Added spreadsheet with WiFi/BT compatible cards

### PR DESCRIPTION
**Pull request by dreamwhite**
Me and @1alessandro1 created a Google Docs spreadsheet for keeping track of supported WiFi/BT chipsets

### CODE REVIEW

**Comment by 5T33Z0** [comment]
Thanks. BTW, I have a **BCM4352** (14e4,43b1) which works in Monterey as well. I think it's not in the list yet

**Comment by dreamwhite** [comment]
Can you tell me what's your WiFi card exact model (such as BCM94352Z) and what kexts are you using?
Thanks

**Comment by 5T33Z0** [comment]
Broadcom BCM94352HMB DW1550, 802.11 a/b/g/n/ac

AirPortBrcmFixup + BcrmPatchRAM and support Kext

**Comment by dreamwhite** [comment]
The reason it works is due to the AirportBrcmFixup injectors that macOS recognizes.

We created the spreadsheet with native supported ids but we can adapt it later to include the manually injected ones from AirportBrcmNICInjector

**Pull request merged**
