### PR TITLE
[K_Debugging] Correct wrong info about OpenCore's SysReport 

### PR DESCRIPTION
**Pull request by 1alessandro1**
I noticed that in this paragraph there were some misconceptions about how OpenCore's sysreport feature works.

If there're any questions feel free to ask below

### CODE REVIEW

**Comment by 5T33Z0** [comment]
Thanks for your suggestions. 

1. But instead of linking to a generic prebuilt EFI which might be outdated at some point, it would be more useful to know which settings have to be made so that the dump wokrs without a bootable config – independent of the OC version.

2. As far as dumping the Audio Codec is concerned: I compared the files created by SysReport vs the one I created in Linux and it seems that all required info is contained within the SysReport dump, so Linux is no longer required.

**Comment by 1alessandro1** [comment]
> But instead of linking to a generic prebuilt EFI which might be outdated at some point, it would be more useful to know which settings have to be made so that the dump wokrs without a bootable config – independent of the OC version.

The prebuilt EFI is there for those who haven't already installed macOS and require to get the most logs out of their firmware/configuration, and it has the minimal config.plist setup to boot OpenCore and log as much info as possible

(The sysreport setting alone is able to debug motherboard/laptop model, ACPI tables, PCI info, Audio etc which is 99.9% of what is required to make an EFI)

If the user requires to log only a certain parameter or to get to know more about a specific event (e.g. if a driver is loaded correctly, or a Kext is preloaded correctly) then he can read OpenCore's `Configuration.pdf` since everything is already documented thetr

**Comment by 5T33Z0** [comment]
Okay. But I correct the text myself.

**Comment by 5T33Z0** [comment]
I was following this [guide](https://www.root86.com/blog/40/entry-51-guide-anleitung-patch-applehda-bedingt-auch-f%C3%BCr-codec-erstellung-in-applealc/) for building an AppleALC layout-id. And with the Codec dump by OpenCore generating the svg with visualizes the audio rrouting of the codec does not work. With the dump from Linux (as I'Ve written before) it does work.

**Pull request closed without merging**
